language: r

sudo: false
cache: packages
warnings_are_errors: false


before_install:
  - tlmgr install standalone showexpl imakeidx xpatch

install:
  - openssl aes-256-cbc -K $encrypted_b316d6cc7b96_key -iv $encrypted_b316d6cc7b96_iv -in tools/deploy_key.enc -out .deploy_key -d
  - chmod 600 .deploy_key
  - eval `ssh-agent -s`
  - ssh-add .deploy_key

script: make manual-git

after_success: tools/deploy.sh

notifications:
  email: false

