language: generic

addons:
  apt:
    packages:
    - texlive-xetex
    - pandoc

script: bash ./tools/deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "edff7f8e0b40"
  - COMMIT_AUTHOR_EMAIL: "travis@circuit.tikz"
